// <auto-generated />
using System;
using CSaver.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSaver.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109152238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSaver.DB.Models.Delivery", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("DOLocationID")
                        .HasColumnType("int");

                    b.Property<int>("PULocationID")
                        .HasColumnType("int");

                    b.Property<float>("fare_amount")
                        .HasColumnType("real");

                    b.Property<int>("passenger_count")
                        .HasColumnType("int");

                    b.Property<string>("store_and_fwd_flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("tip_amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("tpep_dropoff_datetime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("tpep_pickup_datetime")
                        .HasColumnType("datetime2");

                    b.Property<float>("trip_distance")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("tpep_pickup_datetime", "tpep_dropoff_datetime", "passenger_count")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
